Name : Diksha Shravan Patil                                     
Branch : Computer Engg. (CO)                                              
Task 03

In [1]:
import numpy as dikshu

In [41]:
 # 1 array()
arr = dikshu.array([1,2,3,4,5])

In [21]:
arr 

array([1, 2, 3, 4, 5])

In [42]:
# 2 block()
a = dikshu.array([[1, 2], [3, 4]])
b = dikshu.array([[5, 6]])
c = dikshu.block([[a], [b]]) # block()



In [10]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
#3 cross()
a = dikshu.array([1, 0, 0])
b = dikshu.array([0, 1, 0])
c = dikshu.cross(a, b)


In [12]:
c

array([0, 0, 1])

In [44]:
#4  bool_()
x = dikshu.bool_(5)



In [19]:
x


np.True_

In [45]:
# 5 choose()
choices = [dikshu.array([10, 20, 30]), dikshu.array([40, 50, 60])]
index_array = dikshu.array([0, 1, 0])
res = dikshu.choose(index_array, choices)


In [23]:
res

array([10, 50, 30])

In [46]:
#6  clip()
a = dikshu.array([1, 5, 10, 15])
b = dikshu.clip(a, 3, 12)


In [25]:
b

array([ 3,  5, 10, 12])

In [35]:
#7 cumsum()
a = dikshu.array([1, 2, 3, 4])
b = dikshu.cumsum(a)


In [27]:
b

array([ 1,  3,  6, 10])

In [36]:
#8 repeat()
a = dikshu.array([1, 2, 3])
b = dikshu.repeat(a, 2)
b


array([1, 1, 2, 2, 3, 3])

In [37]:
# 9 reshape()
a = dikshu.array([1, 2, 3, 4, 5, 6])
b = dikshu.reshape(a, (2, 3))
b


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
 # 10 unique()
a = dikshu.array([1, 2, 2, 3, 4, 4, 4, 5])
b = dikshu.unique(a)
b


array([1, 2, 3, 4, 5])

In [48]:
 # 11 argsort()
a = dikshu.array([30, 10, 20])
b = dikshu.argsort(a)
b


array([1, 2, 0])

In [53]:
 # 12 argmax() 
a = dikshu.array([5, 10, 3, 8])
max_index = dikshu.argmax(a)
max_index

np.int64(1)

In [54]:
# 13 argmin()
a = dikshu.array([5, 10, 3, 8])
min_index = dikshu.argmin(a)
min_index

np.int64(2)

In [55]:
#14 where()
a = dikshu.array([1, 2, 3, 4, 5])
b = dikshu.array([10, 20, 30, 40, 50])

condition = a > 3
result = dikshu.where(condition, a, b)
result


array([10, 20, 30,  4,  5])

In [57]:
# 15 concatenate
a = dikshu.array([4, 5])
b = dikshu.array([10, 20, 30, 40, 50])

result = dikshu.concatenate((a, b))
result


array([ 4,  5, 10, 20, 30, 40, 50])

In [58]:
# 16 sort()
a = dikshu.array([3, 1, 2, 5, 4])
b = dikshu.sort(a)
b


array([1, 2, 3, 4, 5])

In [59]:
#17 partition() 
a = dikshu.array([7, 2, 5, 3, 9])
b = dikshu.partition(a, 3)
b


array([2, 3, 5, 7, 9])

In [60]:
# 18 intersect1d()
a = dikshu.array([1, 2, 3, 4])
b = dikshu.array([3, 4, 5, 6])
c = dikshu.intersect1d(a, b)
c


array([3, 4])

In [61]:
#19 flip()
a = dikshu.array([1, 2, 3, 4, 5])
b = dikshu.flip(a)
b


array([5, 4, 3, 2, 1])

In [62]:
#20 trace()
a = dikshu.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = dikshu.trace(a)
b


np.int64(15)